### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by kairikeymaster**
Specific questions or remarks:

line 20: I don't know what you mean to say here: "Share your daily or your colorful life online." Why do you say "or"? "Daily life" is a compound noun, so "daily" can't be contrasted with "colorful" as if they are two alternative adjectives you could choose to describe "life." You could have a "colorful life" or a "colorful daily life," but those mean different things: the first means that you've had a lot of interesting and unusual experiences *throughout* your life; the second means that you have a lot of interesting experiences on any given day.

line 181: This explanation is a little unclear: "You can set a future task by changing its start time." I would recommend explaining it slightly differently. For instance, you might say something like, "If you want this task to appear on your daily list before the day it is due, set an earlier start time." However, I did not make this change because I don't understand how the "Auto" start time is computed, and that information would affect how you should describe the custom start time (see my comments for line 606).

line 329: I wasn't sure what you meant by "Most function support using with network except world~\n" so please check that my translation makes sense.

line 352: I think there is something wrong with the variable %2$d because my header card says I've completed 2 out of 3 when I have actually completed 2 out of 4. When I click on the Day section, it shows that I still have 2 remaining.

line 601: I recommend including a link to this github file after you say that help is welcome :)

line 606: "Auto (According to Repeat Frequency)" does not make it clear when the start time will be. It would be helpful to describe somewhere how the start time is determined automatically -- for instance, in the description on line 181. 

line 675: I wasn't sure what you meant by "Only item that is still not used will be put in here," so please double-check my translation. 
   
lines 843-849; 863-869; 897-901: Starter -> Scholar -> Bachelor -> Master is not a natural hierarchy in English (at least not American English). There isn't one specific hierarchy that you have to use, but "Scholar" and "Bachelor" are not terms we would use to identify a person with a certain level of expertise. "Scholar" just means someone with an academic career, and "Bachelor" is really only used to refer to unmarried men. I replaced them with Novice, Journeyman, Expert, Master, but you could also say "Intermediate" instead of Journeyman or "Proficient" instead of Expert; I just don't think those sound good as nouns. 

lines 875-881: I wasn't sure what "mega" or "nia" meant, and I couldn't find anything about them in English sources that could be connected to the traits of intelligence/knowledge and endurance. I thought "scholar" made sense for intelligence and "marathoner" for endurance. I also thought "leader" was too broad for vitality: I think "dynamo" fits better. I wasn't sure what "travel artist" was supposed to mean, but the best thing I could come up with for charm/charisma was "celebrity."

line 1096: I don't know what "It induces vote" means.

lines 1303-1307: I replaced several periods with exclamation points because the periods would have been interpreted by many English speakers as dour, disheartening, or even sarcastic. "Let's get this done." gives the impression that the task is necessary, but will be difficult and unpleasant. "Let's get this done!" would be interpreted as encouraging and enthusiastic, which is something most English speakers want in a productivity app. And many younger Americans in particular would read "Congrats, work timer is over." as insincere, because "congrats"/"congratulations" is almost universally followed by an exclamation point.

line 1353: I don't know where "sell out" is meant to appear, but just in case, I should mention that "sell out" specifically means "sell all available inventory." If I were to "sell out" of tomatoes, I would have no tomatoes left: if I had five, I would sell five; if I had 100, I would sell 100. If you just mean "sell," remove the word "out."

lines 1556-1557: I'm not sure what "Synthesis Cost Item" or "Synthesis Got Item" mean.

line 1576; lines 1688-1689: I'm not sure what context a lot of these phrases are used in, so it's difficult for me to assess whether they are translated properly.

line 1696: I don't know what this means: "Out step count is calculated by the difference of the total step count."

line 1716: I don't know what this means: "Don\'t prompt temporarily"

line 1781: I don't know what you mean by "it\'s using the simple way to implement so that it may be not working well with some actions"

Other:
- It's not clear that "Normal" means that a task will not repeat. For repeat frequency, you should change "Normal" to "No repeat" or "None"
- I can't find an explanation for what "Ebbinghaus" means under the repeat section: does it mean repeats will become less frequent over time? How quickly? When will they stop?
- Keep in mind that the word "weekday" refers to Monday, Tuesday, Wednesday, Thursday, and Friday. "Day of the week" includes all of the previous as well as Saturday and Sunday. (I know, it's stupid, but the days of the weekend don't count as "weekdays" because they don't occur "during the (work) week.")
- In case I missed any, the button to acknowledge or dismiss a popup/hint should say "OK" instead of "YES"
- I didn't have the time to go through and change every instance of these, but "Attention:" would be better translated as "Warning:"
- You use the word "entrance" several times, but I don't know what this means in the context of software.

### CODE REVIEW

**Comment by Ayagikei** [comment]
Hello kairikeymaster,
Thanks for your great work.

Sorry that I am not the native speaker of English, some expressions below may be weird. 

line20:
Acutally it means that you can post the daily activities to the "World".
I prefer the "colorful life" one.

line 181, line 606:
The auto start time is calculated like:
when completed a task with with deadline Jan. 7th, 23:59:59,
If its repeat frequency is daily(1), its start time will be calculated as Jan. 7th 00:00:00. (deadline - 1 day)
If its repeat frequency is weekly(7), its start time will be calculated as Jan. 1st 00:00:00. (deadline - 7 days)

For other example:
when completed a **daily** task with with deadline Jan. 2nd, 04:00:00,
Its start time will be calculated as Jan. 1st 04:00:00. (deadline - 1 day)

In other words, the duration will be calculated to be same as the repeat frequency.
But it's hard to find a word to describe it.

line 352:
Thanks for the feedback, I will look into it.

line 601:
We will add it.

line 1096:
It means something like calling on others to vote online for something.

line 1353:
It should be "Sell", thanks.

lines 1556-1557:
The Synthesis feature is about consuming (costing?) some items and get some others.

line 1576; lines 1688-1689:
They're some description of the Unlock Condition settings of adding custom achievements.

line 1696:
Acutally I want to mean that the step count is calculated by subtraction.
The daily step count = The total step count obtained today - The total step count obtained yesterday

line 1716:
Something like "Don't show this dialog before next crash", but I want it to be shorter text.

Other:
- "None" would be better.
- Ebbinghaus forgetting curve. It's a special repeatation.
  Today→1 day later→2 days later→4 days later→7 days later→15 days later→30 days later
- "weekday" repeat, 😃  I know that , but I can hardly find a short word to describe it well.
- I will check and repalce the "YES" and "Attention", thanks for the reminding.
- "Entrance", I want to mean "the way of opening the specify screen(page) or dialog"


I will check the changes later,
**Thanks you again.**

**Review by Ayagikei — APPROVED** [review]

**Comment by kairikeymaster** [comment]
Hi Kei,

Apologies, I didn't see all these responses when you sent them! Thank you
so much for taking the time to answer my questions, this has been
really helpful. And thank you for the Google Play redemption codes. I have
been loving your app and it has been improving my life a lot.

I have been writing down some suggestions for additions or fixes to the app
beyond translations, but I don't want you to think that this means I don't
value all your hard work and appreciate the app as it is! I would
ordinarily submit a feedback message, but there's a lot of stuff here and I
didn't want to type it all out on my phone. I'm going to separate these
suggestions into low-, medium-, and high- priority categories. Some are
just potential ideas, but others are more seriously impacting my experience
with the app.

High-priority suggestions/issues:

   - When I complete a repeating task that has a reminder, I still receive
   the reminder for that day, but I don't need it and it confuses me. For
   example, if I have a reminder set for 5pm on April 4th, but I complete the
   task at 4pm on April 4th, the reminder still goes off at 5pm on April 4th,
   even though the task for that day is done. Could you set it so that
   completing the task for that repetition also shifts the reminders to the
   next repetition?
   - Is it possible to have an option to leave an overdue repeating task at
   its current repetition and just label it "overdue"? Sometimes I have
   repeated tasks in which *each* repetition *must* be done, even if I do
   them after the deadline. So if I'm overdue, there should be options to say
   "give up," "complete," or "keep overdue." With "keep overdue," I would
   still get the punishment from giving it up, but the task would remain on
   top of my list, with a deadline that has already passed, and some sort of
   "OVERDUE" sticker on the task. It shouldn't move to the next repetition
   until I have completed the current one that is overdue. (This should also
   be an option for non-repeating tasks: even if I pass the deadline, I still
   usually have to do the task, so I need an option to continue using the app
   while acknowledging that the task is overdue and leaving it where it is on
   the task list.) I know this additional option might make the UI more
   cluttered, but if you scroll down to the end of this email, I have a
   suggestion for how to streamline the task-editing UI!
   -
   - Non-repeating overdue tasks move to the bottom of the list when I sort
   by deadline, but it would make a lot more sense for them to remain
at the *top
   *of the list until I complete them or give up on them.
   -
   - In the most recent update of the app, the back arrow button <- on the
   task editing screen is not working for me anymore.

Medium-priority suggestions:

   - Could you show the price of items in the shop that have already been
   purchased (the ones in the Inventory)? I use coins in the app to represent
   real-life money, and I'd like an easier way to see how much I have spent
   (not including coins I have lost for failing tasks). Including prices in
   the purchase history would also be good.
   - When sorting tasks by deadline, it would make more sense to place
   tasks that have a deadline date without a specific time at the *end *of
   the list of tasks due on that date. A task due at the end of the day is
   basically due at 11:59pm, so it should go *after* a task that is due at
   7:00pm, not before.
   - When I edit tasks, this interrupts my streaks. This is bad because I
   often add new subtasks, or change the deadline time, or change the reminder
   time, but the task itself hasn't changed -- it should still count as a
   repetition of the same task.
   - Could you set it so that, when entering the task editing screen, the
   keyboard doesn't pop up and automatically start editing the task name?
   Usually when I'm going in to edit a task, I'm changing the deadline or
   punishment, rarely the title; and when I try to scroll down, I accidentally
   start typing on the keyboard and have to delete the typos.

Low-priority suggestions:

   -
   -
   -
   -
   - It would be very helpful to have a way to see *net *coin gains/losses
   over specified periods of time (for example, if I spent/lost ¥15 this week
   but gained ¥20, show a net of ¥5 for this week)
   - It's a little bit annoying that, when you edit a deadline, start time,
   or reminder, the clock on which you set the time and date defaults to right
   now, rather than remaining at the most recently set time for that task. If
   I set a task's reminder for April 6th at 5pm, when I try to edit the
   reminder, the clock's starting position should be April 6th at 5pm, not
   right now (April 4th at 6:21pm).
   - It's also weird that the subtask date/time entry box is different from
   those in the Extra section.
   - Could there be an option for rewards to increase by a certain amount
   with every consecutive day completed (i.e., with each day that continues a
   streak)?
   - Could you make the colors of individual tasks visible in the widget?
   - Could we have the option to postpone a single occurrence of a
   recurring event? Sometimes I don't want to Freeze or Give Up an event, but
   I have another reason for needing to skip it.
   - It might be good to have a setting where people could choose if they
   want to make the Pomodoro timers automatically proceed. For example, if I
   finish my work timer, the break timer starts right away without us having
   to click the button.
   -
   - Could there be a visual way to indicate importance on the task list
   and the widget? For example: brightness of color, bold font, outlines with
   specific colors or patterns (red outline or borders for LV4 tasks, orange
   for LV3, etc.), or even just big, bold exclamation points (*!!!!* for
   LV4, *!!!* for LV3, etc.).


Idea to improve UI of task edit screen:
I think a great solution for the problem of clutter is exactly what you've
already done with the "MORE OPTIONS" button, which currently expands the
"Extra" section. I think the more common functions should be split up into
three sections, all of which would be visible by default: the "Basics"
section would include color, Task name, and Subtasks; the "Reward &
Punishment" section would include Importance, Difficulty, Attributes, Coin
Reward, Exp Reward, and Punishment Factor; and the "Time" section would
include Start Time, Deadline, Repeat Frequency, and Reminder Time. But then
there could be a small button within each section that expands the section
to show more complex functions, the same way the Extra section expands when
you press "MORE OPTIONS." For example:

   - the "Time" subsection could expand to include "Check Repeat," "Task
   Type," "Overdue Options," and "Target Times."
   - the "Reward & Punishment" section could expand to include "Punishment
   without reward," "Past-deadline increasing punishments" (each day a task is
   overdue, give the punishment again, or give an even bigger punishment),
   "Streak increasing rewards" (each day you continue a streak, you get a
   bigger reward), and "Task-specific reward" (the specific item you get for
   achieving this particular task).
   - the "Basic" section could be made more compact, and could expand to
   include "Notes" and more details on individual subtasks, or any other
   functions you might think of.

The expand button could be very small. I've seen a lot that are just
upside-down carets like this:
ˇ
Those buttons are always very intuitive to me, but you could also include
an explanation in the ? button. You could put the expander button at the
bottom right corner of each section, or to the left of the ? button at the
top.

Thank you so much for taking my input before. I know this is a lot of stuff
to ask, but I don't expect you to address all of it.  Thank you for all
your time and consideration, and thanks for creating such a great and
unique app! I love that I can finally motivate myself to accomplish things
by tying it to concrete monetary rewards. I use the coins to manage my "fun
budget" :)

Sincerely,
Anna Sedlacek

**Comment by Ayagikei** [comment]
Hello Anna,
Thanks for the suggestions!

I will reply to high-priority part of it first:
- The reminders of completed tasks should be removed currently. I will look into this isuue. I want to know which reminder you are using. (Notification or system calendar)
- "Keep overdue"
We will consider adding this feature, But this will cause some changes in the processing flow in the code, we need to evaluate it. Thanks for the UI suggestion too. (In fact, we are refactoring the code in preparation for subsequent optimization of the add/edit tasks UI)
- Non-repeating overdue tasks sort. We will fix it in the feture versions.
- the back arrow button <- on the task editing screen not working.
We have released a minor version to fix this issue recently.

**Comment by kairikeymaster** [comment]
Thank you so much! I am using push notifications for reminders.

Sincerely,
Anna Sedlacek

**Pull request merged**
